### ISSUE TITLE
Travis CI/CD failing  for grab_berekely test but locally its working 

### ISSUE THREAD

**Issue by abhishekanand** [toddschultz/DegreesOfClimateChange#22]
# Issue Template

### Local Run
* [aa@AAMac ~/data515/DegreesOfClimateChange/DegreesOfClimateChange/tests]$ python test_grab_berkeley.py
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK

### Travis 

```
======================================================================
ERROR: DegreesOfClimateChange.tests.test_grab_berkeley (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: DegreesOfClimateChange.tests.test_grab_berkeley
Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/python/3.6.3/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/toddschultz/DegreesOfClimateChange/DegreesOfClimateChange/tests/test_grab_berkeley.py", line 18, in <module>
    from grab_berkeley import grab_berkeleydf
ModuleNotFoundError: No module named 'grab_berkeley'
======================================================================

```

**Comment by abhishekanand** [comment]
Thanks, @toddschultz  for fixing this.
